[package]
name = "aman-vault"
version = "2.0.1"
description = "AMAN - Secure Local Desktop Vault for Windows"
authors = ["Abdullah Al-Makhlafi"]
edition = "2021"

[lib]
name = "aman_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
